2019-05-03 14:29:43.2670||DEBUG|AlgarCliSiTef.Program|init main |url: |action: 
2019-05-03 14:30:10.9429|6|FATAL|Microsoft.AspNetCore.Hosting.Internal.WebHost|Application startup exception Core.Exceptions.BusinessException: Exception of type 'Core.Exceptions.BusinessException' was thrown.
   at Core.Utils.TefMessages.PinpadErrors(Int32 value) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\Core\Utils\TefMessages.cs:line 90
   at AlgarCliSiTef.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\AlgarCliSiTef\Startup.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.ApplicationInsights.HostingStartup.ApplicationInsightsLoggerStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()|url: |action: 
2019-05-03 14:33:56.0596||DEBUG|AlgarCliSiTef.Program|init main |url: |action: 
2019-05-03 14:34:28.7119||ERROR|AlgarCliSiTef.Middleware.ErrorHandlingMiddleware|Exception of type 'Core.Exceptions.BusinessException' was thrown. Core.Exceptions.BusinessException: Exception of type 'Core.Exceptions.BusinessException' was thrown.
   at Core.TEF.Service.TEFService.RealizaTransacao(RechargeCommand rechargeCommand) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\Core\TEF\Service\TEFService.cs:line 75
   at AlgarCliSiTef.Controllers.ValuesController.Post(RechargeCommand rechargeCommands) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\AlgarCliSiTef\Controllers\ValuesController.cs:line 27
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AlgarCliSiTef.Middleware.ErrorHandlingMiddleware.<Invoke>d__2.MoveNext() in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\AlgarCliSiTef\Middleware\ErrorHandlingMiddleware.cs:line 28|url: http://localhost/api/algarTelecom/tef/transacao|action: Post
2019-05-03 14:38:15.6851||DEBUG|AlgarCliSiTef.Program|init main |url: |action: 
2019-05-03 14:39:10.7333||ERROR|AlgarCliSiTef.Middleware.ErrorHandlingMiddleware|Exception of type 'Core.Exceptions.BusinessException' was thrown. Core.Exceptions.BusinessException: Exception of type 'Core.Exceptions.BusinessException' was thrown.
   at Core.TEF.Service.TEFService.RealizaTransacao(RechargeCommand rechargeCommand) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\Core\TEF\Service\TEFService.cs:line 75
   at AlgarCliSiTef.Controllers.ValuesController.Post(RechargeCommand rechargeCommands) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\AlgarCliSiTef\Controllers\ValuesController.cs:line 27
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AlgarCliSiTef.Middleware.ErrorHandlingMiddleware.<Invoke>d__2.MoveNext() in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\AlgarCliSiTef\Middleware\ErrorHandlingMiddleware.cs:line 28|url: http://localhost/api/algarTelecom/tef/transacao|action: Post
2019-05-03 14:41:10.0353||DEBUG|AlgarCliSiTef.Program|init main |url: |action: 
2019-05-03 14:59:38.9043||DEBUG|AlgarCliSiTef.Program|init main |url: |action: 
2019-05-03 15:24:30.6856||DEBUG|AlgarCliSiTef.Program|init main |url: |action: 
2019-05-03 15:25:46.5268||ERROR|AlgarCliSiTef.Middleware.ErrorHandlingMiddleware|Exception of type 'Core.Exceptions.BusinessException' was thrown. Core.Exceptions.BusinessException: Exception of type 'Core.Exceptions.BusinessException' was thrown.
   at Core.TEF.Service.TEFService.RealizaTransacao(RechargeCommand rechargeCommand) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\Core\TEF\Service\TEFService.cs:line 75
   at AlgarCliSiTef.Controllers.ValuesController.Post(RechargeCommand rechargeCommands) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\AlgarCliSiTef\Controllers\ValuesController.cs:line 27
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AlgarCliSiTef.Middleware.ErrorHandlingMiddleware.<Invoke>d__2.MoveNext() in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\AlgarCliSiTef\Middleware\ErrorHandlingMiddleware.cs:line 28|url: http://localhost/api/algarTelecom/tef/transacao|action: Post
2019-05-03 16:00:07.0052||DEBUG|AlgarCliSiTef.Program|init main |url: |action: 
2019-05-03 16:00:34.8355||DEBUG|AlgarCliSiTef.Program|init main |url: |action: 
2019-05-03 16:00:57.3735|6|FATAL|Microsoft.AspNetCore.Hosting.Internal.WebHost|Application startup exception Core.Exceptions.BusinessException: Exception of type 'Core.Exceptions.BusinessException' was thrown.
   at Core.Utils.TefMessages.PinpadErrors(Int32 value) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\Core\Utils\TefMessages.cs:line 90
   at AlgarCliSiTef.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\AlgarCliSiTef\Startup.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.ApplicationInsights.HostingStartup.ApplicationInsightsLoggerStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()|url: |action: 
2019-05-03 16:10:42.3394||DEBUG|AlgarCliSiTef.Program|init main |url: |action: 
2019-05-03 16:11:08.3914|6|FATAL|Microsoft.AspNetCore.Hosting.Internal.WebHost|Application startup exception Core.Exceptions.BusinessException: Exception of type 'Core.Exceptions.BusinessException' was thrown.
   at Core.Utils.TefMessages.PinpadErrors(Int32 value) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\Core\Utils\TefMessages.cs:line 90
   at AlgarCliSiTef.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Users\heitor.araujo\source\repos\AlgarCliSiTef\AlgarCliSiTef\Startup.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.ApplicationInsights.HostingStartup.ApplicationInsightsLoggerStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()|url: |action: 
2019-05-03 16:16:49.0553||DEBUG|AlgarCliSiTef.Program|init main |url: |action: 
